# Generated by Django 3.2.3 on 2021-10-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=40)),
                ('mail', models.CharField(max_length=80)),
                ('login', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=10)),
                ('greenhouses', models.CharField(max_length=4000)),
            ],
        ),
    ]
