# Generated by Django 3.2.3 on 2021-10-15 08:20

from django.db import migrations, models
import smart_greenhouse.models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Greenhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificator', models.CharField(default=smart_greenhouse.models.make_uuid, max_length=40)),
                ('light', models.BooleanField()),
                ('water', models.BooleanField()),
                ('wind', models.BooleanField()),
                ('history', models.JSONField(default=smart_greenhouse.models.history_default)),
                ('status', models.CharField(default=smart_greenhouse.models.status_ok, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=40)),
                ('identificator', models.CharField(default=smart_greenhouse.models.make_uuid, max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='greenhouses',
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default=smart_greenhouse.models.status_user, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='greenhouses',
            field=models.ManyToManyField(to='smart_greenhouse.Greenhouse'),
        ),
    ]
